defaults:
  - /transforms@transforms: camelyon16_transforms

_target_: datamodules.camelyon16.CAMELYON16RandomPatchDataSet
_recursive_: False

path: /project/robertsc/examode/CAMELYON16

train: train
train_frac: 0.95

spacing: 0.5
spacing_tolerance: 0.15
patch_size:
  - 128
  - 128

n_patches_per_wsi: 1000
