
defaults:
  - trainer: ddp_trainer
  - model: vq_ae
  - datamodule@train_datamodule: camelyon16_datamodule
  - utils: [seed_everything]
  - override hydra/launcher: submitit_lisa
  - _self_

utils:
  _target_: instantiate_dictified_listconf
  recursive: False

hydra:
  job:
    env_set:
      HYDRA_FULL_ERROR: "1"
    env_copy:
      - CAMELYON16_PATH