
defaults:
  - trainer: ddp_trainer
  - model: cnn_classifier
  - datamodule: camelyon16_embeddings_datamodule
  - utils: [seed_everything]
  - override hydra/launcher: submitit_snellius
  - _self_

utils:
  _target_: utils.conf_helpers.instantiate_dictified_listconf
  _recursive_: False

trainer:
  log_every_n_steps: 5
  benchmark: False

hydra:
  job:
    env_set:
      HYDRA_FULL_ERROR: '1'
    env_copy:
      - CAMELYON16_EMBEDDINGS_PATH
      - PYTORCH_CUDA_ALLOC_CONF