
defaults:
  - trainer: ddp_trainer
  - trainer/callbacks: [elements_per_second,channels_last]
  - model: vq_ae
  - datamodule@train_datamodule: camelyon16_datamodule
  - utils: [seed_everything]
  - override hydra/launcher: submitit_lisa
  - _self_

utils:
  _target_: utils.conf_helpers.instantiate_dictified_listconf
  _recursive_: False

hydra:
  sweep:
    subdir: ${hydra:job.num}_${hydra:job.id}
  job:
    env_set:
      HYDRA_FULL_ERROR: "1"
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"
    env_copy:
      - CAMELYON16_PATH
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback
