
_target_: pytorch_lightning.Trainer

gpus: "-1"
accelerator: ddp
replace_sampler_ddp: True

benchmark: True

num_sanity_val_steps: 0
precision: 16

log_every_n_steps: 50
val_check_interval: 0.5
flush_logs_every_n_steps: 100
weights_summary: full

max_epochs: 1000