normalize: # default values taken from albumentations
  _target_: 'albumentations.Normalize'
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
  max_pixel_value: 255
