defaults:
  - /transforms@transforms: camelyon16_embeddings_transforms

_target_: datamodules.camelyon16.CAMELYON16EmbeddingsDataset

path: ${oc.env:CAMELYON16_EMBEDDINGS_PATH}

train: train
train_frac: 0.90