defaults:
  - /transforms@transforms: camelyon16_transforms

_target_: datamodules.camelyon16.CAMELYON16RandomPatchDataSet

path: ${oc.env:CAMELYON16_PATH}

train: train
train_frac: 0.90

spacing: 0.5
spacing_tolerance: 0.15
patch_size:
  - 256
  - 256

n_patches_per_wsi: 1000
