defaults:
  - plugins: []
  - callbacks: [tqdm_progress_bar, model_summary]
  - logger: tensorboard_logger

_target_: pytorch_lightning.Trainer

accelerator: auto
devices: auto

num_sanity_val_steps: -1 # useful to get a baseline performance of your model
precision: 32

log_every_n_steps: 50
val_check_interval: 1.0

max_epochs: 1000

plugins:
  _target_: utils.conf_helpers.instantiate_dictified_listconf
  _recursive_: False

callbacks:
  _target_: utils.conf_helpers.instantiate_dictified_listconf
  _recursive_: False
