defaults:
  - dataloader@train_dataloader_conf: default_dataloader
  - dataloader@val_dataloader_conf: default_dataloader
  - override dataloader/dataset@train_dataloader_conf.dataset: camelyon16_dataset
  - override dataloader/dataset@val_dataloader_conf.dataset: camelyon16_dataset
  - _self_

_target_: datamodules.default.DefaultDataModule

train_dataloader_conf:
  _partial_: True
  batch_size: 16

val_dataloader_conf:
  _partial_: True
  batch_size: ${mul:2,${train_datamodule.train_dataloader_conf.batch_size}}
  shuffle: False
  drop_last: False
  dataset:
    train: validation
    path: ${train_datamodule.train_dataloader_conf.dataset.path}
