defaults:
  - dataloader@train_dataloader_conf: camelyon16_embeddings_dataloader
  - dataloader@val_dataloader_conf: camelyon16_embeddings_dataloader

_target_: datamodules.default.DefaultDataModule

val_dataloader_conf:
  dataset:
    train: validation
    path: ${datamodule.train_dataloader_conf.dataset.path}
  shuffle: False
  drop_last: False