defaults:
  - dataloader@train_dataloader_conf: camelyon16_embeddings_dataloader
  - dataloader@val_dataloader_conf: camelyon16_embeddings_dataloader

_target_: datamodules.camelyon16.CAMELYON16EmbeddingsDatamodule

val_dataloader_conf:
  dataset:
    train: validation
    path: ${datamodule.train_dataloader_conf.dataset.path}
  shuffle: False
  batch_size: 1 # because we don't want to crop validation elements