defaults:
  - dataloader@train_dataloader_conf: default_dataloader
  - dataloader@val_dataloader_conf: default_dataloader
  - override dataloader/dataset@train_dataloader_conf.dataset: camelyon16_dataset
  - override dataloader/dataset@val_dataloader_conf.dataset: camelyon16_dataset

_target_: datamodules.default.DefaultDataModule

train_dataloader_conf:
  _partial_: True

val_dataloader_conf:
  _partial_: True
  dataset:
    train: validation
    path: ${train_datamodule.train_dataloader_conf.dataset.path}
  shuffle: False
